container:
  image: cirrusci/flutter:stable

test_task:
  pub_cache:
    folder: ~/.pub-cache
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  test_script: flutter test

analyze_task:
  pub_cache:
    folder: ~/.pub-cache
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  analyze_script: flutter analyze